mysite/Nav/urls.py
from django.conf.urls import url

from . import views


urlpatterns = [
 #   url(r'^$', views.index, name='index'),
    url(r'^$', views.home, name='home'),
    url(r'^getTree/',views.getTree,name="getTree"),
	url(r'^getGroupTree/',views.getGroupTree,name="getGroupTree"),
	url(r'^edit_file/',views.edit_file,name="edit_file"),
	url(r'^save_file/',views.save_file,name="save_file"),
	url(r'^edit_file4group/',views.edit_file4group,name="edit_file4group"),
	url(r'^save_file4group/',views.save_file4group,name="save_file4group"),
]

mysite/Users/urls.py
from django.conf.urls import url

from . import views
from . import info
from . import task_handle
from . import group
from . import manage,build

urlpatterns = [
 #   url(r'^$', views.index, name='index'),
    url(r'^login/', views.login, name='login'),
    url(r'^sign_up/',views.sign_up, name='sign_up'),
    url(r'^add_user/',views.add_user,name='add_user'),
    #url(r'^check/',views.check,name='check'),
    url(r'^identify/',views.identify,name='identify'),
    url(r'^upload/',views.upload,name='upload'),
    url(r'^mkdir/',views.mkdir,name='mkdir'),
    url(r'^logout/',views.logout,name='logout'),
	url(r'^del_file4user/',views.del_file,name="del_file"),
	url(r'^down_fileofuser/',views.download,name="download"),
	
	#--------------------info--------------------------------
	url(r'^info/', info.user_info, name='user_info'),
	url(r'^profile/',info.profile,name="profile"),
	url(r'^update_account/', info.update_account, name='update_account'),
	url(r'^update_email/', info.update_email, name='update_email'),
	url(r'^account/',info.account,name="account"),
	url(r'^email/',info.email,name="email"),
	url(r'^history/',info.history,name="history"),
	url(r'^log/',views.log,name="log"),
	url(r'^test_request/',task_handle.test_request,name="test_request"),
	
	#--------------------group-------------------
	url(r'^group_page/',group.index, name="index_page"),
	url(r'^my_group/',group.my_group,name="my_group"),
	url(r'^teams_work/',group.teams_work,name="teams_work"),
	url(r'^go2group/(?P<group_id>[0-9]*)/$', group.go2group,name="go2group"), 
	url(r'^create_group/',group.create_group,name="create_group"),
	url(r'^create_group_project/',group.create_group_project,name="create_group_project"),
	url(r'^upload_group_project_file/',group.upload,name="upload_group_project_file"),
	url(r'^group_invite/',group.invite,name="group_invite"),
	url(r'^invitations/',views.invitations,name="inv"),
	url(r'^reply_inv/(?P<group_id>[0-9]*)/(?P<reply>[a-z]*)/(?P<au>[0-9]*)/$', group.reply_inv,name="reply"), 
	url(r'^del_file/',group.del_file,name="del_file"),
	url(r'^down_fileofgroup/',group.download,name="download"),
	url(r'^check4group/',group.check,name="check4group"),
	url(r'^report4group/',group.report,name="report4group"),
	url(r'^stream4group_get/',group.stream4group_get,name="stream4group_get"),
	url(r'^build4group/',build.build4group,name="build4group"),
	
	#---------------------manage-------------------
	url(r'^manage/(?P<group_id>[0-9]*)/$',manage.index,name="manage"),
	url(r'^manage/',manage.index,name="manage"),
	url(r'^au_update/',manage.au_update,name="authority4group update"),
	url(r'^group_au_settings/',manage.group_au_settings,name="group_au_settings"),
	url(r'^change_au/',manage.change_au,name="change authority as a member//priority"),
	url(r'^change_au_memlist/',manage.memlist,name="change_au_memlist"),
	url(r'^change_au4member/',manage.change_au4member,name="change_au4member"),
	url(r'^memlist4del/',manage.memlist4del,name="memlist4del"),
	url(r'^delete_member/',manage.delete_member,name="delete_member"),
	url(r'^au4pj_change/',manage.au4pj_change,name="au4pj_change"),
	url(r'^mem_au4pj/',manage.mem_au4pj,name="mem_au4pj"),
	url(r'^pj_au/',manage.pj_au,name="pj_au"),
	url(r'^pj_au_ml/',manage.pj_au_ml,name="pj_au_ml"),
	
	#---------------------task_list--------------------
	url(r'^task_list4user/',task_handle.task_list4user,name="record"),
	url(r'^task_list4group/',task_handle.task_list4group,name="record"),
	
]

mysite/files/urls.py
from django.conf.urls import url

from . import views

app_name = "files"

urlpatterns = [
	url(r'^$', views.index, name='temp_index'), # temporary index
	url(r'^upload/$', views.myFBsite.upload_file, name='upload'),
	url(r'^index/$', views.myFBsite.file_browse, name='browse'),
	url(r'^newdrct/$', views.myFBsite.create_dir, name='create_dir'),
	url(r'^detail/$', views.myFBsite.detail, name='detail'),
	url(r'^delete/$', views.myFBsite.delete, name='f_delete'),
	url(r'^download/$', views.myFBsite.download, name='f_download'),
	# url(r'^success/$', views.success, name='success'),
]

mysite/maintest/urls.py
from django.conf.urls import url

from . import views

app_name = "maintest"

urlpatterns = [
	url(r'^$',views.index, name='index'),
	url(r'^index/$', views.index, name='index'),
	url(r'^arith_result/$', views.arithmetic_app, name='arith_result'),
	url(r'^tv_ajax/$',   views.treeview_ajax, name='tv_ajax'),
	url(r'^save_file/$', views.save_file, name='save_file'),
	url(r'^check/$', views.check, name='check'),
	url(r'^build/$', views.build, name='build'),
	url(r'^test/$', views.test, name='test'),
	url(r'^report/$', views.report, name='report'),
	url(r'^edit_file/$', views.edit_file, name='edit_file'),

]

mysite/mysite/urls.py
from django.conf.urls import include, url
# from django.contrib import admin
import admin
from filebrowser.sites import site

urlpatterns = [
	url(r'^Users/', include('Users.urls', namespace="Users")),
	url(r'^admin/filebrowser/', include(site.urls)),
	url(r'^admin/', admin.site.urls),
	url(r'^grappelli/', include('grappelli.urls')),
	url(r'^polls/', include('polls.urls')),
	url(r'^files/', include('files.urls')),
	url(r'^maintest/', include('maintest.urls',namespace="maintest")),
	url(r'^',include('maintest.urls')),
	url(r'^Nav/',include('Nav.urls')),
	
	#url(r'^admin/', admin.site.urls),
	# url(r'^Users/', include('Users.urls', namespace="Users")),

]

mysite/maintest/models.py
from django.db import models


class Project(models.Model):
	user = models.CharField(max_length=30)  # Use user model
	project_name = models.CharField(max_length=30)
	start_time = models.TimeField()  # DateField, DateTimeField, TimeField
	last_modified_time = models.TimeField()
	status = models.CharField(max_length=4)
	major_files = models.TextField()
	minor_files = models.TextField()
	generated_files = models.TextField()

mysite/maintest/mytools/models.py
import time
import os
import json


class Project(object):
	def __init__(self, name, user, path):
		self.name = name
		self.user = user
		self.path = path
		self.start_time = time.time()
		self.last_modified = time.time()
		self.status = {'check': 0, 'build': 0, 'test': 0, 'report': 0}
		self.major_files = {}
		self.minor_files = {}
		self.generated_files = {}

	def close(self):
		self.last_modified = time.time()
		# format time: time.asctime(time.localtime(time.time()))
		data_path = os.path.join(self.path, 'project_data.json')
		with open(data_path, "w+") as f:
			json.dump(self.__dict__, f)

	def details(self):
		print('\n'.join(['%s = %s' % item for item in self.__dict__.items()]))

	def destroy(self):
		pass


def test():
	project = Project('counter', 'kcl', '.')
	project.details()
	project.close()


if __name__ == '__main__':
	test()

mysite/maintest/views.py
from django.shortcuts import render
from django.http import HttpResponse, HttpResponseRedirect
from django.core.files.storage import DefaultStorage, default_storage, FileSystemStorage
from django.core.urlresolvers import reverse
from django.core.files.storage import DefaultStorage, default_storage, FileSystemStorage
from django.http import StreamingHttpResponse
from django.views.decorators.csrf import csrf_exempt
from django.conf import settings

from filebrowser.sites import site
from filebrowser.base import FileListing, FileObject
import os, json, re
from .mytools.patternGen import PatternGen
from .mytools.mytools import VcdFile, vcd_merge

import time

# patternGen.prepare()

# define
DONE = 2
LOADING = 1
UNDONE = 0
# end define

# Create your views here.

DIRECTORY = os.path.join(site.storage.location, "Users","all_users")  # /path/to/mysite/uploads/
#DIRECTORY = os.path.join("Users","all_users")
"""
Arithmetic app functions
"""


def _file_process(file, regex):
	dict = {}
	with open(file, "r") as fp:
		for line in fp.readlines():
			# print(line)
			m = regex.match(line)
			if m:
				dict[m.group(1)] = m.group(2)
	return dict


def data_parser(file):
	regex = re.compile(r'(data\d): (\d+)')
	return _file_process(file, regex)


def operator_parser(file):
	regex = re.compile(r'(operator): (0x80{6}\d)')
	return _file_process(file, regex)


def app_execution(data1, data2, operator):
	return_value = os.popen('sudo /BR0101/arith_math/arithmetic_intr_mmap_test_app' + data1 + data2 + operator).read()
	return return_value


def arithmetic_app(request):
	# TODO: ugly code.
	dataFile = os.path.join(DIRECTORY, "myTest/data")
	operatorFile = os.path.join(DIRECTORY, "myTest/operator")
	dataDict = data_parser(dataFile)
	operator = operator_parser(operatorFile)['operator']
	result = app_execution(dataDict['data1'], dataDict['data2'], operator)
	# result = app_execution(dataDict["data1"], dataDict["data2"], operator)
	return HttpResponse(result)


"""
Main test template
"""


def treeview_parser(root='', abspath='', relpath='', flag='C'):
	"""
	According to the given root, traverse its file tree and return a json object.
	:param root:
	:param abspath:
	:param flag: 'C'-> Complete file tree, 'O'-> file tree used in open project
	:return:
	"""
	dataList = []
	path = os.path.join(DIRECTORY, root)
	filelisting = FileListing(path, sorting_by='date', sorting_order='desc')
	for item in filelisting.listing():
		fileobject = FileObject(os.path.join(path, item))
		newabspath = os.path.join(abspath, item)
		# print(newabspath)
		if flag == 'O':
			dataList.append({
				"text": item,
				"icon": "glyphicon glyphicon-folder-close",
				# "selectedIcon": "glyphicon glyphicon-folder-open",
				"nodes": treeview_parser(fileobject.path_relative_directory, newabspath, flag=flag),
				"href": reverse('maintest:index') + "?path=" + newabspath
			})
		elif fileobject.is_folder:  # and not fileobject.is_empty:
			dataList.append({
				"text": item,
				"icon": "glyphicon glyphicon-folder-close",
				# "selectedIcon": "glyphicon glyphicon-folder-open",
				"nodes": treeview_parser(fileobject.path_relative_directory, newabspath, flag=flag)
			})
		elif flag == 'C':
			dataList.append({
				"text": item,
				"icon": "glyphicon glyphicon-file",
				"href": reverse('maintest:index') + "?file=" + newabspath + "&path=" + relpath
				# "href": "#edit-text"
			})
	return dataList


def clr_status(request):
	for item in request.session['stream_status']:
		item[1] = UNDONE


def file_check(request):
	pass


def syntax_check(request):
	pass


def check(request):
	query = request.GET
	# self.tfo_path = os.path.join(DIRECTORY, query.get('path', ''))
	request.session['tfo_path'] = request.session['directory']
	request.session['tfo_name'] = query.get('tfo', '')
	print('tfo_path =', request.session['tfo_path'])
	print('tfo_name =', request.session['tfo_name'])
	# tfo_file = 'tfo_demo.tfo'
	# TODO: Check file integrity and syntax.
	request.session['stream_status'][0][1] = DONE  # Check status
	return HttpResponse('check success')


def build(request):
	from maintest.mytools.batch import batch_build
	query = request.GET
	path = query.get('path', '')
	print('initialization success!')
	tfo_path = request.session['tfo_path']
	tfo_name = request.session['tfo_name']
	print('path = {}\ntfo = {}'.format(tfo_path, tfo_name))
	batch_build(tfo_path, tfo_name)
	print('write success!')
	request.session['stream_status'][1][1] = DONE  # Build status
	return HttpResponse("Build Success!")


def test(request):
	from maintest.mytools.batch import batch_test
	try:
		tfo_path = request.session['tfo_path']
		tfo_name = request.session['tfo_name']
		print('path = {}\ntfo = {}'.format(tfo_path, tfo_name))
		batch_test(tfo_path, tfo_name)
		request.session['stream_status'][2][1] = DONE
		return HttpResponse('Test Success!')
	except Exception as err:
		return HttpResponse(err)


def report(request):
	from maintest.mytools.batch import batch_trf2vcd, batch_merge
	try:
		tfo_path = request.session['tfo_path']
		tfo_name = request.session['tfo_name']
		print(tfo_path, tfo_name)
		batch_trf2vcd(tfo_path, tfo_name)
		batch_merge(tfo_path, tfo_name)
		request.session['stream_status'][3][1] = DONE
		return HttpResponse('Report ready!')
	except Exception as err:
		return HttpResponse(err)


def treeview_ajax(request):
	username = request.session.get("username",None)
	if username:
		query = request.GET
		query_dir = query.get('dir', '')
		query_flag = query.get('flag', '')
		path = os.path.join(DIRECTORY, username ,query_dir)
		request.session['directory'] = path  # change root directory of the page
		# print('ajax_path', request.session['directory'])
		request.session['project_name'] = query_dir
		#request.session['wave_path'] = os.path.join(site.storage.location, "maintest/static/maintest/img", username ,query_dir)
		#request.session['wave_path'] = os.path.join("maintest/static/maintest/img", username ,query_dir)
		clr_status(request)
		# if not os.path.exists(request.session['wave_path']):
			# os.mkdir(request.session['wave_path'])
		result = treeview_parser(path, flag=query_flag)
	else:
		result = [{"text":"login first!"}]
	return HttpResponse(json.dumps(result), content_type='application/json')
	


def edit_file(file_path):
	import binascii
	if os.path.isfile(file_path):
		with open(file_path, 'rb+') as f:
			content = f.read()
			if os.path.splitext(file_path)[1] == '.ptn':
				pattern = re.compile('.{32}')
				content = str(binascii.hexlify(content)).lstrip("b'").upper()
				content = '\t'.join(re.findall(r'.{4}', content))
				content = '\n'.join(re.findall(r'.{40}', content))
		# print(type(content))
		return content
	else:
		return "edit your file here."


@csrf_exempt  # WTF
def save_file(request):
	if request.method == 'POST':
		try:
			# print(request.POST)
			content = request.POST['text']
			path = request.POST['path']
			with open(path, 'w') as f:
				f.write(content)
			return HttpResponse("Success!")
		except Exception as exc:
			return HttpResponse(exc)


def index(request):
	"""
	:param request:
	:return: file path,
	"""
	# initialize session
	status = [
		["Check", UNDONE],
		["Build", UNDONE],
		["Test", UNDONE],
		["Report", UNDONE]
	]
	request.session.setdefault('stream_status', status)
	username = request.session.get("username",None)
	if username:
		
		#request.session.setdefault('directory', DIRECTORY)
		
		query = request.GET
		query_file = query.get('file', 'open file')
		# print('query_file(in index)=', query_file)
		directory = request.session.get('directory', username)
		file_path = os.path.join(directory, query_file)
		# print('file_path(in index)=', file_path)
		# print(query_file, file_path)
		query_path = query.get('path', '')
		obj = treeview_parser(directory, relpath=query_path)
		# print(obj)
		tv_dir = treeview_parser(os.path.join(DIRECTORY, username), flag='O')
		# print(self.directory)
		#wave_path = os.path.join('maintest/static/maintest/img', username, '/wave.jpg')
		return render(request, 'maintest/test.html', {
			'DIRECTORY': DIRECTORY,
			'current_path': username,   # directory is Bad URL
			'file_content': edit_file(file_path),  # file to display in <textarea>
			'file_path': file_path,  # path of the above
			'file_name': query_file,
			# 'wave_path': request.session.get("wave_path",wave_path),  # can't deal with it
			'obj': json.dumps(obj),  # default treeview object
			'tv_dir': json.dumps(tv_dir),
			'stream_status': request.session.get('stream_status', []),  # stream status
			'username':username,
		})
	else:
		return render(request, 'maintest/test.html', {
			'stream_status': request.session.get('stream_status', [])  # stream status
		})


# class MainTest(object):
# 	wave_path = ''
# 	project_name = ''
#
# 	def __init__(self, storage=default_storage):
# 		self.directory = DIRECTORY
# 		self.stream_status = [
# 			["Check", UNDONE],
# 			["Build", UNDONE],
# 			["Test", UNDONE],
# 			["Report", UNDONE]
# 		]  # TODO: extend the item.
#
# 	def clr_status(self):
# 		for item in self.stream_status:
# 			item[1] = UNDONE
#
# 	def file_check(self, request):
# 		pass
#
# 	def syntax_check(self, request):
# 		pass
#
# 	# def check(self, request):
# 	# 	query = request.GET
# 	# 	# self.tfo_path = os.path.join(DIRECTORY, query.get('path', ''))
# 	# 	self.tfo_path = self.directory
# 	# 	self.tfo_name = query.get('tfo', '')
# 	# 	print('path = {}\ntfo = {}'.format(self.tfo_path, self.tfo_name))
# 	# 	print('directory =', self.directory)
# 	# 	# tfo_file = 'tfo_demo.tfo'
# 	# 	# self.pattern = PatternGen(self.tfo_path, self.tfo_name)
# 	# 	# TODO: Check file integrity and syntax.
# 	# 	self.stream_status[0][1] = DONE  # Check status
# 	# 	return HttpResponse('check success')
#
# 	def check(self, request):
# 		query = request.GET
# 		# self.tfo_path = os.path.join(DIRECTORY, query.get('path', ''))
# 		request.session['tfo_path'] = self.directory
# 		request.session['tfo_name'] = query.get('tfo', '')
# 		print('directory =', self.directory)

mysite/maintest/templates/maintest/test.html
<!DOCTYPE html>
<html lang="zh-CN">
</head>
{% load static %}
<meta charset="utf-8">
<title>Test App in Bootstrap!</title>
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<!--<script src="http://cdn.static.runoob.com/libs/jquery/2.1.1/jquery.min.js"></script>-->
<script type="text/javascript" src="{% static 'maintest/js/jquery.js' %}"></script>
<!--<link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" rel="stylesheet">-->
<link rel="stylesheet" href="{% static 'maintest/bootstrap/css/bootstrap.css' %}">
<!--<script src="http://cdn.static.runoob.com/libs/bootstrap/3.3.7/js/bootstrap.min.js"></script>-->
<script type="text/javascript" src="{% static 'maintest/bootstrap/js/bootstrap.min.js' %}"></script>


<script type="text/javascript" src="{% static 'maintest/js/bootstrap-treeview.js' %}"></script>
<link rel="stylesheet" type="text/css" href="{% static 'maintest/css/bootstrap-treeview.css' %}">
<!--<script src="https://cdn.bootcss.com/bootstrap-treeview/1.2.0/bootstrap-treeview.min.css"></script>-->
<!--<script src="https://cdn.bootcss.com/bootstrap-treeview/1.2.0/bootstrap-treeview.min.js"></script>-->

<script type="text/javascript" src="{% static 'maintest/js/maintest_js.js' %}"></script>
<link rel="stylesheet" type="text/css" href="{% static 'maintest/css/maintest.css' %}">
<script>
    // define django template tag variables
    var build_url = "{% url 'maintest:build' %}";
    var check_url = "{% url 'maintest:check' %}";
    var test_url = "{% url 'Users:test_request' %}";
    var report_url = "{% url 'maintest:report' %}";
    var tv_ajax_url = "{% url 'maintest:tv_ajax' %}";


</script>
<script>
    var currentTVPath = '';  //delete when class MainTest available.

    $(document).ready(function()
    {
      $("#typical-test").click(function()  //to delete
      {
        html = '<form>Location:<input type="text" id="t-p-path"></form>';
        $("#s-p-body").html(html);
      });
      $("#submit-t-p-path").click(function() //submit path to be opened
      {
        currentTVPath = $('#t-p-path').val();
        loadTreeview(currentTVPath);
        $('#strat-project-modal').modal('hide')
      });
      $("#refresh_tree").click(function()  //refresh the file tree
      {
        loadTreeview(currentTVPath);
      });
    });


</script>
<script>  //unfinished
    $(document).ready(function(){
      $(".expand-icon").click(function(){
        console.log('hello2');
        console.log($(this).attr("data-nodeid"));
        console.log('hello3');
        //$(this).nextElementSibling.attr("class", "glyphicon-folder-open");
      });
    });


</script>
<script>
    $(document).ready(function(){
      $("[href=#edit_text]").click(function(){
        console.log('select file');
      });
      $("#submit-edit-text").click(function(){
        console.log('start editing file');
        var text = $("#edit-text").val();
        var data = {
          text: text,
          path: "{{file_path}}"
        };
        $.ajax({
          type: 'POST',
          url: "{% url 'maintest:save_file' %}",
          data: data,
          success: function(data){
            console.log(data);
            if(data == 'Success!')
              alert("修改成功!");
            else
              alert("修改失败QAQ!\n" + data);
          }
        });
      });
    });

    function uploadFile(path){
      window.location.href = "{% url 'files:browse' %}?dir=" + path;
    }


</script>
<script>
    // FOR STUDY



</script>
</head>

<body>
<!--<div class="page-header">-->
<!--<h1>&nbsp;Chip-Test App-->
<!--<small>testing</small>-->
<!--</h1>-->
<!--</div>-->
<div class="container">
	<div>
		{% include "maintest/include/account.html" %}
	</div>
	
  <div class="row">
    <div class="col-md-3" style="vertical-align:middle;font-size:20px">
      <p>&nbsp;Chip-Test App
        <small>testing</small>
      </p>
    </div>
	
	
	
    <div class="col-md-6">
      <!--Toolbar-->
      {% include "maintest/include/toolbar.html" %}
    </div>
    <div class="col-md-3">
      <!--Search bar-->
      <!--<div class="input-group">-->
        <!--<input type="text" class="form-control">-->
        <!--<span class="input-group-btn">-->
                        <!--<button class="btn btn-default" type="button">Search!</button>-->
                    <!--</span>-->
      <!--</div>&lt;!&ndash; /input-group &ndash;&gt;-->
    </div><!-- /.col-lg-6 -->
  </div>
  <br>

  <div class="row">
    <div class="col-md-3"
         style="background-color: #dedef8;box-shadow:
                   inset 1px -1px 1px #444, inset -1px 1px 1px #444;">
      <h4>tool window</h4>
      <div class="row">
        <div class="col-md-12"
             style="background-color: #dedef8;box-shadow:
                           inset 1px -1px 1px #444, inset -1px 1px 1px #444;">
          <p>file tree</p>
          <div id="tree"></div>
          <a onclick="uploadFile(currentTVPath)" class="btn btn-default">
            upload <span class="glyphicon glyphicon-upload"></span>
          </a>
          <button id="refresh_tree" type="button" class="btn btn-default">
            refresh <span class="glyphicon glyphicon-refresh"></span>
          </button>
          <br><br>
        </div>
      </div>
      <div class="row">
        <div class="col-md-12"
             style="background-color: #dedef8;box-shadow:
                           inset 1px -1px 1px #444, inset -1px 1px 1px #444;">
          <p>stream</p>
          {% include "maintest/include/stream_status.html" %}
        </div>
      </div>
    </div>
    <div class="col-md-9"
         style="background-color: #dedef8;box-shadow:
                   inset 1px -1px 1px #444, inset -1px 1px 1px #444;">
      <!--load the selected file an edit it here-->
      <div class="row">
        <div class="col-md-12"
             style="background-color: #ffffff;box-shadow:
                           inset 1px -1px 1px #444, inset -1px 1px 1px #444;padding:10px;">
          <ul id="myTab" class="nav nav-tabs">
            <li class="active">
              <a href="#home" data-toggle="tab">
                {{file_name}}
              </a>
            </li>
            <li class="pull-right">
              <button id="submit-edit-text" type="submit" class="btn btn-default">submit</button>
            </li>
            <!--<li><a href="#ios" data-toggle="tab">iOS</a></li>-->
            <!--<li class="dropdown">-->
            <!--<a href="#" id="myTabDrop1" class="dropdown-toggle"-->
            <!--data-toggle="dropdown">Java-->
            <!--<b class="caret"></b>-->
            <!--</a>-->
            <!--<ul class="dropdown-menu" role="menu" aria-labelledby="myTabDrop1">-->
            <!--<li><a href="#jmeter" tabindex="-1" data-toggle="tab">jmeter</a></li>-->
            <!--<li><a href="#ejb" tabindex="-1" data-toggle="tab">ejb</a></li>-->
            <!--</ul>-->
            <!--</li>-->
          </ul>
          <div id="myTabContent" class="tab-content">
            <div class="tab-pane fade in active" id="home">
              <textarea id="edit-text" class="form-control" rows="10">{{ file_content }}</textarea>
            </div>
            <div class="tab-pane fade" id="ios">
              <p>some comtent</p>
            </div>
          </div>
          <!--<label for="name">edit area</label>-->
          <!--&lt;!&ndash;<input type="text" class="form-control" id="name" placeholder="selected file">&ndash;&gt;-->
          <!--<textarea id="edit-text" class="form-control" rows="10">{{ file_content }}</textarea>-->
          <!--</div>-->
          <!--<button id="submit-edit-text" type="submit" class="btn btn-default">submit</button>-->
          <!--</form>-->
          <br>
        </div>
      </div>
      <div class="row">
        <h4>Waveform</h4>
        <div class="col-md-12 pre-scrollable"
             style="background-color: #dedef8;box-shadow:
                   inset 1px -1px 1px #444, inset -1px 1px 1px #444;padding:10px;">
          <!--<img src="{{ DIRECTORY }}/{{ current_path }}/wave.jpg" class="img-rounded img-responsive">-->
          <img id="waveform" class="pre-scrollable"
               src="{% static 'maintest/img/' %}{{ current_path }}/{{ current_path }}.jpg"
               class="img-rounded img-responsive">
          <!--<button type="button" onclick="loadXMLDoc_calc()">Calculate</button>-->
          <br>
        </div>
        <!--<p id='#wavedrawing'>-->
        <!--<div style='outline: 1px solid gray;'>-->
          <!--<button id="load">Compile and Draw</button>-->
          <!--<button id="draw" disabled='disabled'>Reload Image</button>-->
        <!--</div>-->
        <!--<div style='outline: 1px solid gray;'>-->
          <!--<ul id="namel"-->
              <!--style='outline: 1px solid green; width:20%;margin:0;display: inline-block;vertical-align:top;list-style-type: square;'></ul>-->
          <!--<ul id='sep'-->
              <!--style='background:url(../../static/maintest/WaveDrawJS/img/sep.png) repeat-y;display: inline-block;width:1%;height:0;margin: 0; padding: 0;list-style-type: none'></ul>-->
          <!--&lt;!&ndash; canvas容器 &ndash;&gt;-->
          <!--<ul id="canvasl"-->
              <!--style='outline: 2px solid white;display: inline-block;width:70%;margin: 0; padding: 0;list-style-type: none;font-size:0'></ul>-->
        <!--</div>-->
        <!--<p>propotion<input id="propotion" type="range" min="0" max="1000" value="1000"></p>-->
        <!--<p>width<input id="width" type="range" min="0" max="1000" value="1000"></p>-->
        <!--<p>scale<input id="scale" type="range" min="0" max="1000" value="1000"></p>-->
        <!--<script src="{% static 'maintest/WaveDrawJS/script/utils.js' %}"></script>-->
        <!--<script src="{% static 'maintest/WaveDrawJS/script/draw.js' %}"></script>-->
        <!--<script src="{% static 'maintest/WaveDrawJS/script/controller.js' %}"></script>-->
        <!--</p>-->
      </div>
    </div>
  </div>
</div>
<script>
   generateFileTree({{obj|safe}});
   treeviewOpenProject({{tv_dir|safe}});
   // waveform_path = "{% static 'maintest/img/' %}{{ current_path }}/";


</script>
<script>
$(function() {
    $('#strat-project-modal').modal('hide')
});


</script>
</body>
</html>