mysite/Nav/urls.py
from django.conf.urls import url

from . import views


urlpatterns = [
 #   url(r'^$', views.index, name='index'),
    url(r'^$', views.home, name='home'),
    url(r'^getTree/',views.getTree,name="getTree"),
	url(r'^getGroupTree/',views.getGroupTree,name="getGroupTree"),
	url(r'^edit_file/',views.edit_file,name="edit_file"),
	url(r'^save_file/',views.save_file,name="save_file"),
	url(r'^edit_file4group/',views.edit_file4group,name="edit_file4group"),
	url(r'^save_file4group/',views.save_file4group,name="save_file4group"),
]

mysite/files/urls.py
from django.conf.urls import url

from . import views

app_name = "files"

urlpatterns = [
	url(r'^$', views.index, name='temp_index'), # temporary index
	url(r'^upload/$', views.myFBsite.upload_file, name='upload'),
	url(r'^index/$', views.myFBsite.file_browse, name='browse'),
	url(r'^newdrct/$', views.myFBsite.create_dir, name='create_dir'),
	url(r'^detail/$', views.myFBsite.detail, name='detail'),
	url(r'^delete/$', views.myFBsite.delete, name='f_delete'),
	url(r'^download/$', views.myFBsite.download, name='f_download'),
	# url(r'^success/$', views.success, name='success'),
]

mysite/mysite/urls.py
from django.conf.urls import include, url
# from django.contrib import admin
import admin
from filebrowser.sites import site

urlpatterns = [
	url(r'^Users/', include('Users.urls', namespace="Users")),
	url(r'^admin/filebrowser/', include(site.urls)),
	url(r'^admin/', admin.site.urls),
	url(r'^grappelli/', include('grappelli.urls')),
	url(r'^polls/', include('polls.urls')),
	url(r'^files/', include('files.urls')),
	url(r'^maintest/', include('maintest.urls',namespace="maintest")),
	url(r'^',include('maintest.urls')),
	url(r'^Nav/',include('Nav.urls')),
	
	#url(r'^admin/', admin.site.urls),
	# url(r'^Users/', include('Users.urls', namespace="Users")),

]

mysite/polls/urls.py
from django.conf.urls import url

from . import views

app_name = 'polls'
urlpatterns = [
    url(r'^$', views.IndexView.as_view(), name='index'),
    url(r'^(?P<pk>[0-9]+)/$', views.DetailView.as_view(), name='detail'),
    url(r'^(?P<pk>[0-9]+)/results/$', views.ResultsView.as_view(), name='results'),
    url(r'^(?P<question_id>[0-9]+)/vote/$', views.vote, name='vote'),
]
'''
#old version
urlpatterns = [
	# ex: /polls/
	url(r'^$', views.index, name='index'),
	# ex: /polls/5/
	# the 'name' value as called by the {% url %} template tag
	url(r'^(?P<question_id>[0-9]+)/$', views.detail, name='detail'),
	# ex: /polls/5/results/
	url(r'^(?P<question_id>[0-9]+)/results/$', views.results, name='results'),
	# ex: /polls/5/vote/
	url(r'^(?P<question_id>[0-9]+)/vote/$', views.vote, name='vote'),
]
'''

mysite/files/models.py
from django.db import models

# Create your models here.

mysite/files/forms.py
import os
import re

from django import forms
from django.utils.translation import ugettext_lazy as _

'''
from filebrowser.settings import FOLDER_REGEX
from filebrowser.utils import convert_filename
'''


class UploadFileForm(forms.Form):

	# title = forms.CharField(max_length=50)
	
	file = forms.FileField(widget=forms.ClearableFileInput(attrs={'multiple': True}))
	

class CreateDirForm(forms.Form):
	"""
	Form for creating a folder.
	"""

	name = forms.CharField(
		widget=forms.TextInput(attrs=dict({'class': 'vTextField'}, 
		max_length=50, min_length=3)), 
		label=_(u'Name'), 
		help_text=_(u'Only letters, numbers, underscores, spaces and hyphens are allowed.'), 
		required=True
		)


class ChangeForm(forms.Form):
	"""
	Form for creating a folder.
	"""

	name = forms.CharField(
		widget=forms.TextInput(attrs=dict({'class': 'vTextField'},
		max_length=50, min_length=3)),
		label=_(u'Name'),
		help_text=_(u'Only letters, numbers, underscores, spaces and hyphens are allowed.'),
		required=True
		)

mysite/files/views.py
from django.shortcuts import render
from django.http import HttpResponse, HttpResponseRedirect
from django.core.urlresolvers import reverse
from django.core.files.storage import DefaultStorage, default_storage, FileSystemStorage
from django.http import StreamingHttpResponse

from .forms import UploadFileForm

from filebrowser.sites import site
from filebrowser.base import FileListing, FileObject
import os

# print(site.storage.location)

# Create your views here.


from django.views.generic.edit import FormView
from .forms import UploadFileForm


class FileFieldView(FormView):
	form_class = UploadFileForm
	template_name = 'files/upload.html'  # Replace with your template.
	success_url = '...'  # Replace with your URL or reverse().

	def post(self, request, *args, **kwargs):
		form_class = self.get_form_class()
		form = self.get_form(form_class)
		files = request.FILES.getlist('file_field')
		if form.is_valid():
			for f in files:
				...  # Do something with each file.
			return self.form_valid(form)
		else:
			return self.form_invalid(form)


def index(request):
	return HttpResponse("This is the file management page.")


def handle_uploaded_file(dir, f):
	with open(os.path.join('./uploads/', dir, f.name), 'wb+') as destination:
		for chunk in f.chunks():
			destination.write(chunk)


def upload_file(request):
	if request.method == 'POST':
		form = UploadFileForm(request.POST, request.FILES)
		if form.is_valid():
			handle_uploaded_file(request.FILES['file'])
			return HttpResponse('upload succed!')
	else:
		form = UploadFileForm()
	return render(request, 'files/upload.html', {
			'form': form,
			'query': query,
			'breadcrumbs': get_Breadcrumbs(query.get('dir', ''))
		})


def get_Breadcrumbs(query):
	# Return a breadcrumb-style navigation bar
	breadcrumbs = []
	temp_path = ''
	if query:
		for item in os.path.split(query):
			temp_path = os.path.join(temp_path, item)
			breadcrumbs.append([item, temp_path])
	return breadcrumbs


class MyFileBrowser(object):
	# filelisting_class = FileListing

	def __init__(self, storage=default_storage):
		self.directory = os.path.abspath('uploads')
		self.storage = storage

	def file_browse(self, request):
		query = request.GET
		query_dir = query.get('dir', '')
		path = u'%s' % os.path.join(site.directory, query_dir)
		# print(site.directory)

		# Return a file list:hehe
		filelisting = FileListing(path, sorting_by='date', sorting_order='desc')
		fileobjects = []
		for filepath in filelisting.listing():
			fileobject = FileObject(os.path.join(site.directory, query_dir, filepath))
			# print(fileobject.path_relative_directory)
			fileobjects.append(fileobject)
		return render(request, 'files/index.html', {
			'query': query,
			'query_dir': query_dir,
			'filelisting': filelisting,
			'breadcrumbs': get_Breadcrumbs(query_dir),
			'fileobjects': fileobjects
			})

	def upload_file(self, request):
		query = request.GET
		query_dir = query.get('dir', '')
		if request.method == 'POST':
			form = UploadFileForm(request.POST, request.FILES)
			print(request.FILES.getlist('file'))
			if form.is_valid():
				handle_uploaded_file(query_dir, request.FILES['file'])
				redirect_url = reverse("files:browse") + '?dir=' + query.get('dir', '')
				return HttpResponseRedirect(redirect_url)
		else:
			form = UploadFileForm()
		return render(request, 'files/upload.html', {
			'form': form,
			'query': query,
			'breadcrumbs': get_Breadcrumbs(query.get('dir', ''))
		})

	def create_dir(self, request):
		
		from .forms import CreateDirForm

		query = request.GET
		query_dir = query.get('dir', '')
		# print(query_dir)
		path = u'%s' % os.path.join(self.directory, query_dir)

		if request.method == 'POST':
			form = CreateDirForm(request.POST)
			if form.is_valid():
				mkdir_path = os.path.join(path, form.cleaned_data['name'])
				os.mkdir(mkdir_path)
				# return HttpResponse('upload succed!')
			redirect_url = reverse("files:browse")
			return HttpResponseRedirect(redirect_url)
		else:
			form = CreateDirForm()

		# return HttpResponse("You can create new directory here.")
		return render(request, 'files/createdir.html', {
			'form': form,
			'query': query,
			'breadcrumbs': get_Breadcrumbs(query.get('dir', ''))
		})

	def delete(self, request):
		"""Delete existing File/Directory."""
		query = request.GET
		path = u'%s' % os.path.join(self.directory, query.get('dir', ''))
		fileobject = FileObject(os.path.join(path, query.get('filename', '')))
		if request.GET:
			try:
				fileobject.delete()
			except OSError:
				# TODO: define error-message
				pass
		redirect_url = reverse("files:browse") + '?dir=' + query.get('dir', '')
		return HttpResponseRedirect(redirect_url)

	def download(self, request):
		query = request.GET
		file_path = u'%s' % os.path.join(site.directory, query.get('dir', ''), query.get('filename', ''))

		def file_iterator(file_name, chunk_size=512):
			with open(file_name, 'rb') as f:
				while True:
					c = f.read(chunk_size)
					if c:
						yield c
					else:
						break

		response = StreamingHttpResponse(file_iterator(file_path))
		response['Content-Type'] = 'application/octet-stream'
		response['Content-Disposition'] = 'attachment;filename="{0}"'.format(file_path)

		return response

	def upload(self, request):
		pass

	def detail(self, request):
		query = request.GET
		path = u'%s' % os.path.join(site.directory, query.get('dir', ''))
		fileobject = FileObject(os.path.join(path, query.get('filename', '')))

		from .forms import ChangeForm

		if request.method == 'POST':
			form = ChangeForm(request.POST)
			# print(form.cleaned_data['name'])
			if form.is_valid():
				new_name = form.cleaned_data['name']
				self.storage.move(fileobject.path, os.path.join(fileobject.head, new_name))
				# return HttpResponse('upload succed!')
			redirect_url = reverse("files:browse")+'?dir='+query.get('dir', '')
			return HttpResponseRedirect(redirect_url)
		else:
			form = ChangeForm()

		return render(request, 'files/detail.html', {
			'form': form,
			'query': query,
			'fileobject': fileobject,
			'breadcrumbs': get_Breadcrumbs(query.get('dir', ''))
		})


myFBsite = MyFileBrowser()

mysite/files/templates/files/createdir.html
{% extends "admin/base_site.html" %}
{% load i18n admin_static admin_modify grp_tags files_tags %}
	<metacharset = "UTF-8">
	{% block title %}Index{% endblock %}
	<!--<title>index</title>-->
	<!--Breadcrumbs-->

{% block content_title %}
    <h1>New Directory</h1>
{% endblock %}

{% block breadcrumbs %}
<ul class="grp-horizontal-list">
	<li><a href="{% url 'files:browse' %}">Home</a></li>
	{% for item in breadcrumbs %}
		<li><a href="{% url 'files:browse' %}?&amp;dir={{ item.1 }}">{{item.0}}</a></li>
	{% endfor %}
</ul>
{% endblock %}

{% block content %}
<form method="post" action="{{ query_string }}" enctype="multipart/form-data">
	{%csrf_token%}
	<fieldset class="grp-module">
		<div class="grp-row {% if form.name.errors %}grp-errors{% endif %}">
			<div class="l-2c-fluid l-d-4">
				<div class="c-1"><label class="required" for="id_name">{{ form.name.label }}</label></div>
				<div class="c-2">
					{{ form.name }}
					{% if form.name.errors %}<ul class="errorlist">{{ form.name.errors }}</ul>{% endif %}
					{% if form.name.help_text %}<p class="grp-help">{{ form.name.help_text|safe }}</p>{% endif %}
				</div>
			</div>
		</div>
	</fieldset>
	<footer class="grp-module grp-submit-row grp-fixed-footer">
            <header style="display:none"><h1>Submit Options</h1></header>
            <ul>
                <li class="grp-float-right"><input type="submit" value="submit" class="grp-button" /></li>
                <li class="grp-float-left"><a href="{% url 'files:browse' %}{% query_string 'dir' %}" class="grp-button">Cancel</a></li>
            </ul>
	</footer>
</form>
{% endblock %}

mysite/files/templates/files/detail.html
{% extends "admin/base_site.html" %}

<!-- JAVASCRIPTS -->
{% block javascripts %}
    {{ block.super }}
    <script type="text/javascript">
    (function($){
        $(document).ready(function() {
            $("div#grp-content-container .grp-collapse").grp_collapsible({
                on_init: function(elem, options) {
                    // open collapse (and all collapse parents) in case of errors
                    if (elem.find("ul.grp-errorlist").length > 0) {
                        elem.removeClass("grp-closed")
                            .addClass("grp-open");
                        elem.parents(".grp-collapse")
                            .removeClass("grp-closed")
                            .addClass("grp-open");
                    }
                }
            });
            // remove edit module if no actions are given
            if ($("select#id_custom_action").find("option").length <= 1) {
                $("fieldset#fieldset_edit").hide();
            }
        });
    })(grp.jQuery);
    </script>
    {{ media }}
{% endblock %}

{% load i18n admin_static admin_modify grp_tags files_tags %}
	<metacharset = "UTF-8">
	{% block title %}Index{% endblock %}
	<!--<title>index</title>-->
	<!--Breadcrumbs-->

{% block content_title %}
    <h1>{{ fileobject.filename }}</h1>
{% endblock %}

{% block breadcrumbs %}
<ul class="grp-horizontal-list">
	<li><a href="{% url 'files:browse' %}">Home</a></li>
	{% for item in breadcrumbs %}
		<li><a href="{% url 'files:browse' %}?&amp;dir={{ item.1 }}">{{item.0}}</a></li>
	{% endfor %}
</ul>
{% endblock %}

{% block content %}
<div id="grp-content-container">
    <form method="post" action="{% query_string 'dir' %}" enctype="multipart/form-data">
	    {%csrf_token%}
        <fieldset class="grp-module">
            <div class="grp-row {% if form.name.errors %}grp-errors{% endif %}">
                <div class="l-2c-fluid l-d-4">
                    <div class="c-1"><label class="required" for="id_name">{{ form.name.label }}</label></div>
                    <div class="c-2">
                        {{ form.name }}
                        <input type="submit" value="submit" class="grp-button" />
                        {% if form.name.errors %}<ul class="errorlist">{{ form.name.errors }}</ul>{% endif %}
                        {% if form.name.help_text %}<p class="grp-help">{{ form.name.help_text|safe }}</p>{% endif %}
                    </div>
                </div>
            </div>
        </fieldset>

        {% if fileobject.filetype == "Folder" %}
        <fieldset class="grp-module grp-collapse grp-open">
            <h2 class="grp-collapse-handler">Folder Information</h2>
            <div class="grp-row">
                <div class="l-2c-fluid l-d-4">
                    <div class="c-1"><label>Date</label></div>
                    <div class="c-2">
                        <p class="grp-text">
                            {{ fileobject.datetime|date:"N j, Y" }}
                        </p>
                    </div>
                </div>
            </div>
        </fieldset>
        {% endif %}
        {% if fileobject.filetype != "Folder" %}
        <fieldset class="grp-module grp-collapse grp-open">
            <h2 class="grp-collapse-handler">File Information</h2>
            <div class="grp-row">
                <div class="l-2c-fluid l-d-4">
                    <div class="c-1"><label>URL</label></div>
                    <div class="c-2">
                        <p class="grp-text">
                            <a href="{{ fileobject.url }}">{{ fileobject.url }}</a>
                        </p>
                    </div>
                </div>
            </div>
            <div class="grp-row">
                <div class="l-2c-fluid l-d-4">
                    <div class="c-1"><label>Filesize</label></div>
                    <div class="c-2">
                        <p class="grp-text">
                            {{ fileobject.filesize|filesizeformat }}
                        </p>
                    </div>
                </div>
            </div>
            <div class="grp-row">
                <div class="l-2c-fluid l-d-4">
                    <div class="c-1"><label>Date</label></div>
                    <div class="c-2">
                        <p class="grp-text">
                            {{ fileobject.datetime|date:"N j, Y" }}
                        </p>
                    </div>
                </div>
            </div>
        </fieldset>
            {% endif %}
        <footer class="grp-module grp-submit-row grp-fixed-footer">
            <header style="display:none"><h1>Submit Options</h1></header>
            <ul>
                <li class="grp-float-left"><a href="{% url 'files:f_delete' %}{% query_string 'dir' %}" class="grp-button grp-delete-link">Delete</a></li>
                <!--<li class="grp-float-right"><input type="submit" value="submit" class="grp-button" /></li>-->
                <li class="grp-float-right"><a href="{% url 'files:f_download' %}{% query_string 'dir' %}" class="grp-button">Download</a></li>
            </ul>
        </footer>
    </form>

    {% endblock %}

mysite/files/templates/files/index.html
{% extends "admin/base_site.html" %}
{% load i18n admin_static admin_modify grp_tags files_tags %}
	<metacharset = "UTF-8">
	{% block title %}Index{% endblock %}
	<!--<title>index</title>-->
	<!--Breadcrumbs-->

{% block content_title %}
    <h1>File Management</h1>
{% endblock %}

{% block breadcrumbs %}
<ul class="grp-horizontal-list">
	<li><a href="{% url 'files:browse' %}">Home</a></li>
	{% for item in breadcrumbs %}
		<li><a href="{% url 'files:browse' %}?&amp;dir={{ item.1 }}">{{item.0}}</a></li>
	{% endfor %}
</ul>
{% endblock %}

{% block object-tools %}
<ul class="grp-object-tools">
	<!--{% block object-tools-items %}-->
		<li><a href="{% url 'files:create_dir' %}{% query_string 'dir' %}">
			New directory</a></li>
		<li><a href="{% url 'files:upload' %}{% query_string 'dir' %}" class="grp-state-focus">
			Upload
		</a></li>
		<li><a href="{% url 'maintest:index' %}">
			Return
		</a></li>
	<!--{% endblock %}-->
</ul>
{% endblock %}

{% block content %}
{{res}}
	<!--Toolbar-->


	<!--File list-->
	<table>
		<thead>
			<tr>
				<th>Filename</th>
				<th>size</th>
				<th>date</th>
				<th></th>
			</tr>
		</thead>
		<tbody>
		{% for item in fileobjects %}
		<tr>
			<!--Filename-->
			<td>
				{% if item.is_folder %}
					<a href="{% url 'files:browse' %}?&amp;dir={{ item.path_relative_directory|urlencode }}">
					<strong>{{ item.filename }}</strong></a>
				{% else %}
					{{ item.filename }}
				{% endif %}
			</td>
			<!--size-->
			<td>{% if item.filesize %}{{ item.filesize|filesizeformat }}{% else %}&mdash;{% endif %}</td>
			<!--date-->
			<td>{{ item.datetime|date:"N j, Y" }}</td>
			<!--detail-->
			<td><a href="{% url 'files:detail' %}?dir={{ query_dir }}&amp;filename={{ item.filename|urlencode }}">
				<!--add tag-->
				<strong>Details</strong>
				</a></td>
		</tr>
		{% endfor %}
		</tbody>
	</table>
	<br>
{% endblock %}
</html>

mysite/files/templates/files/upload.html
{% extends "admin/base_site.html" %}
{% load i18n admin_static admin_modify grp_tags files_tags %}
	<metacharset = "UTF-8">
	{% block title %}Index{% endblock %}
	<!--<title>index</title>-->
	<!--Breadcrumbs-->

{% block content_title %}
    <h1>Upload</h1>
{% endblock %}

{% block breadcrumbs %}
<ul class="grp-horizontal-list">
	<li><a href="{% url 'files:browse' %}">Home</a></li>
	{% for item in breadcrumbs %}
		<li><a href="{% url 'files:browse' %}?&amp;dir={{ item.1 }}">{{item.0}}</a></li>
	{% endfor %}
</ul>
{% endblock %}

{% block content %}
<form method="post" action="{{ query_string }}" enctype="multipart/form-data">
	{%csrf_token%}
	<fieldset class="grp-module">
		<div class="grp-row {% if form.name.errors %}grp-errors{% endif %}">
			<div class="l-2c-fluid l-d-4">
				<div class="c-1"><label class="required" for="id_name">Select a file:</label></div>
				<div class="c-2">
					{{ form }}
				</div>
			</div>
		</div>
	</fieldset>
	<footer class="grp-module grp-submit-row grp-fixed-footer">
            <ul>
                <li class="grp-float-right"><input type="submit" value="submit" class="grp-button" /></li>
                <li class="grp-float-left"><a href="{% url 'files:browse' %}{% query_string 'dir' %}" class="grp-button">Cancel</a></li>
            </ul>
	</footer>
</form>
{% endblock %}